name: C++ Integration Tests
on: push
jobs:
  cpp-integration-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
            triplet: x64-linux-dynamic
          - os: ubuntu-latest
            compiler: clang
            triplet: x64-linux-dynamic
          - os: macos-latest
            compiler: clang
            triplet: x64-osx-dynamic
          - os: windows-latest
            compiler: msvc
            triplet: x64-windows-dynamic
          - os: windows-latest
            compiler: msvc
            arch: x86
            triplet: x86-windows-dynamic
          - os: ubuntu-24.04-arm
            compiler: gcc
            triplet: arm64-linux-dynamic
          - os: ubuntu-24.04-arm
            compiler: clang
            triplet: arm64-linux-dynamic
          - os: windows-11-arm
            compiler: msvc
            triplet: arm64-windows-dynamic
          # - os: windows-latest
          #   compiler: mingw
          #   triplet: x64-mingw-dynamic  # EVENTUALLY: get MinGW working
          # - os: ubuntu-latest
          #   compiler: gcc
          #   arch: x86
          #   # triplet: x86-linux-dynamic  # EVENTUALLY: get dynamic x86 working
          #   triplet: x86-linux
          # - os: ubuntu-latest
          #   compiler: clang
          #   arch: x86
          #   # triplet: x86-linux-dynamic  # EVENTUALLY: get dynamic x86 working
          #   triplet: x86-linux
          # - os: windows-latest
          #   compiler: mingw
          #   arch: x86
          #   # triplet: x86-mingw-dynamic  # EVENTUALLY: get dynamic Windows x86 working
          #   triplet: x86-mingw-static
    runs-on: ${{ matrix.os }}
    env:
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_binary_cache
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_binary_cache
      X_VCPKG_ASSET_SOURCES_CACHE: ${{ github.workspace }}/vcpkg_asset_cache
      X_VCPKG_ASSET_SOURCES: x-azurl,file://${{ github.workspace }}/vcpkg_asset_cache
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        shell: bash
        run: |
          if [[ "${{ matrix.compiler }}" == "gcc" ]]; then
            export CC=gcc
            export CXX=g++
          elif [[ "${{ matrix.compiler }}" == "clang" ]]; then
            export CC=clang
            export CXX=clang++
          elif [[ "${{ matrix.compiler }}" == "mingw" ]]; then
            export CC=x86_64-w64-mingw32-gcc
            export CXX=x86_64-w64-mingw32-g++
          fi

          mkdir ${GITHUB_WORKSPACE}/vcpkg_asset_cache

      - name: Apt dependencies
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install m4 autoconf automake libtool
          fi

      - name: Install vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: '${GITHUB_WORKSPACE}/vcpkg.json'
          # doNotCache: false  # TODO: enable this
        env:
          VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
          VCPKG_DEFAULT_HOST_TRIPLET: ${{ matrix.triplet }}

      - name: Cache vcpkg build
        uses: actions/cache@v4
        with:
          # ${X_VCPKG_ASSET_SOURCES_CACHE}
          path: |
            ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: vcpkg-${{ matrix.compiler }}-${{ matrix.triplet }}-${{ hashFiles('vcpkg.json') }}

      - name: Configure, Build, and Test
        shell: bash
        run: |
          CMAKE_FLAGS=()
          if [ "${{ matrix.arch }}" = "x86" ]; then
            if [ "$RUNNER_OS" = "Windows" ]; then
              CMAKE_FLAGS+=("-A" "Win32")
            else
              CMAKE_FLAGS+=("-D" "CMAKE_C_FLAGS=-m32" "-D" "CMAKE_CXX_FLAGS=-m32")
            fi
          fi

          echo "Default binary cache: ${VCPKG_DEFAULT_BINARY_CACHE}"

          VCPKG_ROOT_POSIX=$(wslpath "${VCPKG_ROOT}" 2>/dev/null || echo "${VCPKG_ROOT}")
          cmake -D CMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT_POSIX/scripts/buildsystems/vcpkg.cmake \
            -D VCPKG_TARGET_TRIPLET=${{ matrix.triplet }} \
            -S . -B build_test "${CMAKE_FLAGS[@]}"

          BUILD_CONFIG_CMAKE=""
          BUILD_CONFIG_CTEST=""
          if [ "$RUNNER_OS" = "Windows" ]; then
            BUILD_CONFIG_CMAKE="--config RelWithDebInfo"
            BUILD_CONFIG_CTEST="-C RelWithDebInfo"
          fi

          cmake --build build_test --target IntegrationTests $BUILD_CONFIG_CMAKE
          ctest --test-dir build_test -V $BUILD_CONFIG_CTEST
